name: VPS Free (Linux Ubuntu Latest)

on:
  schedule:
    - cron: '0 */5 * * *'  # Executar a cada 5 horas

jobs:
  criar-maquina:
    runs-on: ubuntu-latest

    steps:
    - name: Criar Nova Máquina
      run: |
        sudo apt install xfce4 xrdp -y
        sudo passwd root -d
        sudo service xrdp restart
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
        echo "root:040112" | sudo chpasswd
        ngrok tcp 3389
