name: VPS Free (Linux Ubuntu Latest)

on:
  schedule:
    - cron: '0 */5 * * *'  # Executar a cada 5 horas 
  workflow_dispatch:

jobs:
  criar-maquina:
    runs-on: ubuntu-latest

    steps:
    - name: Criar Nova Máquina
      run: |
        docker run zg212/up:x
